name: Style Check

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize] # Rebuild on new pushes to PR

jobs:
  style-check:
    runs-on: ubuntu-20.04     # No need for cmake repo
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          ./util/install_deps_ubuntu.sh assume-yes
          sudo apt-get install --yes cmake
          sudo apt-get install --yes clang-7
          sudo apt-get install --yes clang-format-10
          python -m pip install -U yapf==0.30.0 nbformat
      - name: Run style check
        run: |
          mkdir build
          cd build
          cmake ..
          make check-style
